/**
 * POST /api/dashboard/salesperson/[userId]/send-email
 *
 * Generates a Salesperson Performance Report PDF and emails it to the
 * specified recipient. Admin-only.
 *
 * Request body (JSON):
 *   { to: string, subject: string, message: string }
 *
 * Query params forwarded to getSalespersonDetail:
 *   from, to, tz   (date range + timezone)
 */

import { type NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { requireApiUser, isResponse } from "@/lib/auth/require";
import { isCrmAdminUser } from "@/lib/auth/is-crm-admin";
import { getSalespersonDetail } from "@/lib/services/dashboard/salesperson-detail-service";
import {
  renderSalespersonPdfToBuffer,
  salespersonPdfFileName,
} from "@/lib/services/dashboard/salesperson-pdf-buffer";
import { sendReportEmail } from "@/lib/services/email/send-report";
import { parseOverviewFilters } from "@/lib/services/dashboard/parse-overview-filters";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 30;

const bodySchema = z.object({
  to:      z.string().trim().email("Invalid recipient email address"),
  subject: z.string().trim().min(1).max(200),
  message: z.string().trim().max(2000),
});

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ userId: string }> },
) {
  try {
    const user = await requireApiUser();
    if (isResponse(user)) return user;

    if (!isCrmAdminUser(user)) {
      return NextResponse.json({ success: false, error: "Send report is available to org administrators only." },
        { status: 403 },
      );
    }

    const { userId } = await params;

    // Validate request body
    const rawBody = await req.json().catch(() => null);
    const parsed = bodySchema.safeParse(rawBody);
    if (!parsed.success) {
      return NextResponse.json({ success: false, error: "Validation failed", errors: parsed.error.flatten().fieldErrors },
        { status: 400 },
      );
    }
    const { to, subject, message } = parsed.data;

    // Resolve date range filters from query string
    const filters = parseOverviewFilters(req, user);

    // Fetch salesperson data
    const data = await getSalespersonDetail(user.orgId, userId, filters.range);
    if (!data) {
      return NextResponse.json({ success: false, error: "User not found." }, { status: 404 });
    }

    // Generate PDF buffer
    const buffer = await renderSalespersonPdfToBuffer(data);
    const fileName = salespersonPdfFileName(data.userName);

    // Build plain-text email body
    const textBody = [
      message,
      "",
      "─────────────────────────────────────",
      `Report: ${data.userName}`,
      `Period: ${new Date(data.range.fromIso).toLocaleDateString("en-IN", { dateStyle: "medium" })}` +
        ` – ${new Date(data.range.toIso).toLocaleDateString("en-IN", { dateStyle: "medium" })}`,
      `Activity Score: ${data.kpis.activityScore}`,
      `Leads Created: ${data.kpis.leadsCreated}`,
      `Deals Won: ${data.kpis.dealsWon}`,
      `Revenue: ${data.kpis.revenueWonDisplay}`,
      "─────────────────────────────────────",
      "This report was generated by QuikCRM.",
    ].join("\n");

    // Build HTML email body
    const htmlBody = `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#F1F5F9;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#F1F5F9;padding:32px 16px;">
    <tr><td align="center">
      <table role="presentation" width="560" cellpadding="0" cellspacing="0"
             style="background:#fff;border-radius:12px;border:1px solid #E2E8F0;overflow:hidden;max-width:560px;width:100%;">
        <tr>
          <td style="background:#2563EB;padding:20px 28px;">
            <span style="color:#fff;font-size:17px;font-weight:700;">QuikCRM</span>
            <span style="color:#93C5FD;font-size:12px;margin-left:10px;">Performance Report</span>
          </td>
        </tr>
        <tr>
          <td style="padding:24px 28px 8px;">
            <p style="margin:0;font-size:14px;color:#475569;line-height:1.6;">${message.replace(/\n/g, "<br>")}</p>
          </td>
        </tr>
        <tr>
          <td style="padding:0 28px 24px;">
            <table role="presentation" width="100%" style="background:#F8FAFC;border-radius:8px;border:1px solid #E2E8F0;margin-top:16px;">
              <tr>
                <td style="padding:16px 20px;">
                  <p style="margin:0 0 4px;font-size:13px;font-weight:700;color:#0F172A;">${data.userName}</p>
                  <p style="margin:0 0 12px;font-size:11px;color:#64748B;">
                    ${new Date(data.range.fromIso).toLocaleDateString("en-IN", { dateStyle: "medium" })}
                    &ndash;
                    ${new Date(data.range.toIso).toLocaleDateString("en-IN", { dateStyle: "medium" })}
                  </p>
                  <table role="presentation" style="width:100%;">
                    <tr>
                      <td style="padding:4px 0;font-size:12px;color:#64748B;width:50%;">Activity Score</td>
                      <td style="padding:4px 0;font-size:12px;font-weight:700;color:#2563EB;">${data.kpis.activityScore} / 100</td>
                    </tr>
                    <tr>
                      <td style="padding:4px 0;font-size:12px;color:#64748B;">Leads Created</td>
                      <td style="padding:4px 0;font-size:12px;font-weight:700;color:#0F172A;">${data.kpis.leadsCreated}</td>
                    </tr>
                    <tr>
                      <td style="padding:4px 0;font-size:12px;color:#64748B;">Deals Won</td>
                      <td style="padding:4px 0;font-size:12px;font-weight:700;color:#16A34A;">${data.kpis.dealsWon}</td>
                    </tr>
                    <tr>
                      <td style="padding:4px 0;font-size:12px;color:#64748B;">Revenue</td>
                      <td style="padding:4px 0;font-size:12px;font-weight:700;color:#0F172A;">${data.kpis.revenueWonDisplay}</td>
                    </tr>
                  </table>
                </td>
              </tr>
            </table>
            <p style="margin:16px 0 0;font-size:11px;color:#94A3B8;">
              The full report is attached as a PDF. Generated by QuikCRM.
            </p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`.trim();

    // Send the email — capture result to verify delivery
    const emailResult = await sendReportEmail({
      to: [to],
      subject,
      text: textBody,
      html: htmlBody,
      attachment: { filename: fileName, content: buffer },
    });

    // Diagnostic: log the full result so server logs show exact delivery status
    console.info("[send-email] Email result", {
      driver:    emailResult.driver,
      messageId: emailResult.messageId,
      sentAt:    emailResult.sentAt,
      to,
    });

    return NextResponse.json({
      ok: true,
      message: `Report emailed to ${to} successfully.`,
      // Include driver in response so client can see which transport fired
      _debug: { driver: emailResult.driver, messageId: emailResult.messageId },
    });
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Failed to send report";
    const status = (error as { statusCode?: number })?.statusCode ?? 500;
    if (status >= 500) console.error("[send-email]", error);
    return NextResponse.json({ success: false, error: message }, { status });
  }
}
