-- CrmExpress: tenantId -> orgId (app_quikcrmexpress only).
-- Data-preserving: columns are RENAMED, not dropped/recreated, so existing
-- tenant values survive and satisfy the new FK to quikit."Org".
-- (Prisma's own migrate diff emits DROP+ADD here, which would destroy data.)
--
-- GUARDED: 20260807180000_quikcrmexpress_init now creates these tables directly
-- in their orgId shape, because no migration previously created them at all.
-- On a fresh database there is no tenantId column to rename, so the whole body
-- is skipped. On a legacy database (tables predating the init migration, still
-- carrying tenantId) the original rename runs exactly as before.
DO $guard$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'app_quikcrmexpress'
      AND table_name   = 'CrmLead'
      AND column_name  = 'tenantId'
  ) THEN
    EXECUTE $stmt$-- 1. rename the scoping column on all 79 CrmExpress tables
ALTER TABLE "app_quikcrmexpress"."CrmPermissionTemplate" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmAccount" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmContact" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmLead" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."LeadSquaredSyncMap" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmLeadAttachment" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmLeadListView" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmLeadSavedList" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmLeadSource" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmOpportunity" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmOpportunityClientMeeting" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmOpportunityProduct" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmOpportunityStageTransition" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmActivity" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmTask" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmNote" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmCompanyProfile" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmOrgWorkspaceSettings" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmQuickFilter" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmDashboardPin" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmCampaign" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmLandingPage" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmWebWidget" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmFormDefinition" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmAutomationRule" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmWorkflowDefinition" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmAutomationPendingStep" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmAutomationDistributionState" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmAutomationLeadDayCount" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmAutomationAttribution" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmProcessDefinition" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmSlaRule" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmSlaLeadTracking" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmTelephonyProvider" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmVirtualNumber" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmCallLog" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmCallDisposition" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmCtcCallAudit" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmIndiaVoiceWebhookLog" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmLeadImportJob" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmReportDefinition" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmNotification" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmOutboundMessageLog" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmAttendanceLog" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmSalesTeam" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmSalesGroup" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmAuditLog" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmIntegrationConfig" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmPaymentVerification" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmDocumentFolder" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmDocument" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmDocumentLink" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmProductTaxonomy" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmProduct" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmProductVariant" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmWarehouse" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmProductInventory" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmStockMovement" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmProductImage" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmPriceList" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmPriceListItem" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmPriceListAuditLog" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmQuote" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmQuoteLine" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmQuoteStatusTransition" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmQuoteTemplate" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmQuoteApproval" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmQuotePdfSnapshot" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmQuoteComment" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmQuoteEngagementEvent" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmQuotePortalAccess" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmInvoice" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmSequence" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmOrder" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmOrderLine" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmFormSet" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmFieldValue" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmSetSelectionLog" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmFileAttachment" RENAME COLUMN "tenantId" TO "orgId"$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmAttendanceLog_orgId_idx" ON "app_quikcrmexpress"."CrmAttendanceLog"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmAuditLog_orgId_idx" ON "app_quikcrmexpress"."CrmAuditLog"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmAutomationAttribution_orgId_idx" ON "app_quikcrmexpress"."CrmAutomationAttribution"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmAutomationDistributionState_orgId_idx" ON "app_quikcrmexpress"."CrmAutomationDistributionState"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmAutomationLeadDayCount_orgId_idx" ON "app_quikcrmexpress"."CrmAutomationLeadDayCount"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmAutomationPendingStep_orgId_idx" ON "app_quikcrmexpress"."CrmAutomationPendingStep"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmAutomationRule_orgId_idx" ON "app_quikcrmexpress"."CrmAutomationRule"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmCompanyProfile_orgId_idx" ON "app_quikcrmexpress"."CrmCompanyProfile"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmDashboardPin_orgId_idx" ON "app_quikcrmexpress"."CrmDashboardPin"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmDocument_orgId_idx" ON "app_quikcrmexpress"."CrmDocument"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmDocumentLink_orgId_idx" ON "app_quikcrmexpress"."CrmDocumentLink"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmFieldValue_orgId_idx" ON "app_quikcrmexpress"."CrmFieldValue"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmFileAttachment_orgId_idx" ON "app_quikcrmexpress"."CrmFileAttachment"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmFormSet_orgId_idx" ON "app_quikcrmexpress"."CrmFormSet"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmIntegrationConfig_orgId_idx" ON "app_quikcrmexpress"."CrmIntegrationConfig"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmInvoice_orgId_idx" ON "app_quikcrmexpress"."CrmInvoice"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmLeadAttachment_orgId_idx" ON "app_quikcrmexpress"."CrmLeadAttachment"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmLeadListView_orgId_idx" ON "app_quikcrmexpress"."CrmLeadListView"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmLeadSavedList_orgId_idx" ON "app_quikcrmexpress"."CrmLeadSavedList"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmNote_orgId_idx" ON "app_quikcrmexpress"."CrmNote"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmNotification_orgId_idx" ON "app_quikcrmexpress"."CrmNotification"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmOpportunityClientMeeting_orgId_idx" ON "app_quikcrmexpress"."CrmOpportunityClientMeeting"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmOpportunityProduct_orgId_idx" ON "app_quikcrmexpress"."CrmOpportunityProduct"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmOpportunityStageTransition_orgId_idx" ON "app_quikcrmexpress"."CrmOpportunityStageTransition"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmOrderLine_orgId_idx" ON "app_quikcrmexpress"."CrmOrderLine"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmOrgWorkspaceSettings_orgId_idx" ON "app_quikcrmexpress"."CrmOrgWorkspaceSettings"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmPaymentVerification_orgId_idx" ON "app_quikcrmexpress"."CrmPaymentVerification"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmPriceListAuditLog_orgId_idx" ON "app_quikcrmexpress"."CrmPriceListAuditLog"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmPriceListItem_orgId_idx" ON "app_quikcrmexpress"."CrmPriceListItem"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmProductImage_orgId_idx" ON "app_quikcrmexpress"."CrmProductImage"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmProductInventory_orgId_idx" ON "app_quikcrmexpress"."CrmProductInventory"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmProductTaxonomy_orgId_idx" ON "app_quikcrmexpress"."CrmProductTaxonomy"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmProductVariant_orgId_idx" ON "app_quikcrmexpress"."CrmProductVariant"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmQuickFilter_orgId_idx" ON "app_quikcrmexpress"."CrmQuickFilter"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmQuoteApproval_orgId_idx" ON "app_quikcrmexpress"."CrmQuoteApproval"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmQuoteComment_orgId_idx" ON "app_quikcrmexpress"."CrmQuoteComment"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmQuoteEngagementEvent_orgId_idx" ON "app_quikcrmexpress"."CrmQuoteEngagementEvent"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmQuoteLine_orgId_idx" ON "app_quikcrmexpress"."CrmQuoteLine"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmQuotePdfSnapshot_orgId_idx" ON "app_quikcrmexpress"."CrmQuotePdfSnapshot"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmQuotePortalAccess_orgId_idx" ON "app_quikcrmexpress"."CrmQuotePortalAccess"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmQuoteStatusTransition_orgId_idx" ON "app_quikcrmexpress"."CrmQuoteStatusTransition"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmQuoteTemplate_orgId_idx" ON "app_quikcrmexpress"."CrmQuoteTemplate"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmSequence_orgId_idx" ON "app_quikcrmexpress"."CrmSequence"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmSetSelectionLog_orgId_idx" ON "app_quikcrmexpress"."CrmSetSelectionLog"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmSlaLeadTracking_orgId_idx" ON "app_quikcrmexpress"."CrmSlaLeadTracking"("orgId")$stmt$;
    EXECUTE $stmt$CREATE INDEX "CrmStockMovement_orgId_idx" ON "app_quikcrmexpress"."CrmStockMovement"("orgId")$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmPermissionTemplate" ADD CONSTRAINT "CrmPermissionTemplate_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmAccount" ADD CONSTRAINT "CrmAccount_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmContact" ADD CONSTRAINT "CrmContact_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmLead" ADD CONSTRAINT "CrmLead_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."LeadSquaredSyncMap" ADD CONSTRAINT "LeadSquaredSyncMap_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmLeadAttachment" ADD CONSTRAINT "CrmLeadAttachment_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmLeadListView" ADD CONSTRAINT "CrmLeadListView_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmLeadSavedList" ADD CONSTRAINT "CrmLeadSavedList_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmLeadSource" ADD CONSTRAINT "CrmLeadSource_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmOpportunity" ADD CONSTRAINT "CrmOpportunity_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmOpportunityClientMeeting" ADD CONSTRAINT "CrmOpportunityClientMeeting_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmOpportunityProduct" ADD CONSTRAINT "CrmOpportunityProduct_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmOpportunityStageTransition" ADD CONSTRAINT "CrmOpportunityStageTransition_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmActivity" ADD CONSTRAINT "CrmActivity_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmTask" ADD CONSTRAINT "CrmTask_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmNote" ADD CONSTRAINT "CrmNote_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmCompanyProfile" ADD CONSTRAINT "CrmCompanyProfile_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmOrgWorkspaceSettings" ADD CONSTRAINT "CrmOrgWorkspaceSettings_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmQuickFilter" ADD CONSTRAINT "CrmQuickFilter_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmDashboardPin" ADD CONSTRAINT "CrmDashboardPin_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmCampaign" ADD CONSTRAINT "CrmCampaign_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmLandingPage" ADD CONSTRAINT "CrmLandingPage_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmWebWidget" ADD CONSTRAINT "CrmWebWidget_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmFormDefinition" ADD CONSTRAINT "CrmFormDefinition_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmAutomationRule" ADD CONSTRAINT "CrmAutomationRule_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmWorkflowDefinition" ADD CONSTRAINT "CrmWorkflowDefinition_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmAutomationPendingStep" ADD CONSTRAINT "CrmAutomationPendingStep_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmAutomationDistributionState" ADD CONSTRAINT "CrmAutomationDistributionState_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmAutomationLeadDayCount" ADD CONSTRAINT "CrmAutomationLeadDayCount_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmAutomationAttribution" ADD CONSTRAINT "CrmAutomationAttribution_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmProcessDefinition" ADD CONSTRAINT "CrmProcessDefinition_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmSlaRule" ADD CONSTRAINT "CrmSlaRule_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmSlaLeadTracking" ADD CONSTRAINT "CrmSlaLeadTracking_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmTelephonyProvider" ADD CONSTRAINT "CrmTelephonyProvider_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmVirtualNumber" ADD CONSTRAINT "CrmVirtualNumber_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmCallLog" ADD CONSTRAINT "CrmCallLog_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmCallDisposition" ADD CONSTRAINT "CrmCallDisposition_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmCtcCallAudit" ADD CONSTRAINT "CrmCtcCallAudit_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmIndiaVoiceWebhookLog" ADD CONSTRAINT "CrmIndiaVoiceWebhookLog_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmLeadImportJob" ADD CONSTRAINT "CrmLeadImportJob_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmReportDefinition" ADD CONSTRAINT "CrmReportDefinition_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmNotification" ADD CONSTRAINT "CrmNotification_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmOutboundMessageLog" ADD CONSTRAINT "CrmOutboundMessageLog_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmAttendanceLog" ADD CONSTRAINT "CrmAttendanceLog_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmSalesTeam" ADD CONSTRAINT "CrmSalesTeam_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmSalesGroup" ADD CONSTRAINT "CrmSalesGroup_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmAuditLog" ADD CONSTRAINT "CrmAuditLog_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmIntegrationConfig" ADD CONSTRAINT "CrmIntegrationConfig_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmPaymentVerification" ADD CONSTRAINT "CrmPaymentVerification_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmDocumentFolder" ADD CONSTRAINT "CrmDocumentFolder_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmDocument" ADD CONSTRAINT "CrmDocument_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmDocumentLink" ADD CONSTRAINT "CrmDocumentLink_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmProductTaxonomy" ADD CONSTRAINT "CrmProductTaxonomy_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmProduct" ADD CONSTRAINT "CrmProduct_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmProductVariant" ADD CONSTRAINT "CrmProductVariant_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmWarehouse" ADD CONSTRAINT "CrmWarehouse_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmProductInventory" ADD CONSTRAINT "CrmProductInventory_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmStockMovement" ADD CONSTRAINT "CrmStockMovement_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmProductImage" ADD CONSTRAINT "CrmProductImage_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmPriceList" ADD CONSTRAINT "CrmPriceList_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmPriceListItem" ADD CONSTRAINT "CrmPriceListItem_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmPriceListAuditLog" ADD CONSTRAINT "CrmPriceListAuditLog_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmQuote" ADD CONSTRAINT "CrmQuote_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmQuoteLine" ADD CONSTRAINT "CrmQuoteLine_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmQuoteStatusTransition" ADD CONSTRAINT "CrmQuoteStatusTransition_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmQuoteTemplate" ADD CONSTRAINT "CrmQuoteTemplate_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmQuoteApproval" ADD CONSTRAINT "CrmQuoteApproval_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmQuotePdfSnapshot" ADD CONSTRAINT "CrmQuotePdfSnapshot_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmQuoteComment" ADD CONSTRAINT "CrmQuoteComment_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmQuoteEngagementEvent" ADD CONSTRAINT "CrmQuoteEngagementEvent_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmQuotePortalAccess" ADD CONSTRAINT "CrmQuotePortalAccess_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmInvoice" ADD CONSTRAINT "CrmInvoice_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmSequence" ADD CONSTRAINT "CrmSequence_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmOrder" ADD CONSTRAINT "CrmOrder_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmOrderLine" ADD CONSTRAINT "CrmOrderLine_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmFormSet" ADD CONSTRAINT "CrmFormSet_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmFieldValue" ADD CONSTRAINT "CrmFieldValue_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmSetSelectionLog" ADD CONSTRAINT "CrmSetSelectionLog_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER TABLE "app_quikcrmexpress"."CrmFileAttachment" ADD CONSTRAINT "CrmFileAttachment_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "quikit"."Org"("id") ON DELETE CASCADE ON UPDATE CASCADE$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmAccount_tenantId_defaultPriceListId_idx" RENAME TO "CrmAccount_orgId_defaultPriceListId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmAccount_tenantId_deletedAt_idx" RENAME TO "CrmAccount_orgId_deletedAt_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmAccount_tenantId_idx" RENAME TO "CrmAccount_orgId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmAccount_tenantId_industryKey_idx" RENAME TO "CrmAccount_orgId_industryKey_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmAccount_tenantId_name_idx" RENAME TO "CrmAccount_orgId_name_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmAccount_tenantId_ownerId_idx" RENAME TO "CrmAccount_orgId_ownerId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmAccount_tenantId_parentAccountId_idx" RENAME TO "CrmAccount_orgId_parentAccountId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmAccount_tenantId_segmentEnum_idx" RENAME TO "CrmAccount_orgId_segmentEnum_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmAccount_tenantId_status_idx" RENAME TO "CrmAccount_orgId_status_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmActivity_tenantId_idx" RENAME TO "CrmActivity_orgId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmActivity_tenantId_ownerId_occurredAt_idx" RENAME TO "CrmActivity_orgId_ownerId_occurredAt_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmActivity_tenantId_relatedKind_relatedObjectId_idx" RENAME TO "CrmActivity_orgId_relatedKind_relatedObjectId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmActivity_tenantId_relatedOrphanedAt_idx" RENAME TO "CrmActivity_orgId_relatedOrphanedAt_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmActivity_tenantId_sourceSystem_externalId_key" RENAME TO "CrmActivity_orgId_sourceSystem_externalId_key"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmAttendanceLog_tenantId_userId_idx" RENAME TO "CrmAttendanceLog_orgId_userId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmAuditLog_tenantId_createdAt_idx" RENAME TO "CrmAuditLog_orgId_createdAt_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmAuditLog_tenantId_module_resourceId_idx" RENAME TO "CrmAuditLog_orgId_module_resourceId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmAuditLog_tenantId_userId_createdAt_idx" RENAME TO "CrmAuditLog_orgId_userId_createdAt_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmAutomationAttribution_tenantId_engineSource_idx" RENAME TO "CrmAutomationAttribution_orgId_engineSource_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmAutomationAttribution_tenantId_leadId_createdAt_idx" RENAME TO "CrmAutomationAttribution_orgId_leadId_createdAt_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmAutomationDistributionState_tenantId_workflowId_nodeId_key" RENAME TO "CrmAutomationDistributionState_orgId_workflowId_nodeId_key"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmAutomationLeadDayCount_tenantId_leadId_day_key" RENAME TO "CrmAutomationLeadDayCount_orgId_leadId_day_key"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmAutomationLeadDayCount_tenantId_terminated_idx" RENAME TO "CrmAutomationLeadDayCount_orgId_terminated_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmAutomationPendingStep_tenantId_status_resumeAt_idx" RENAME TO "CrmAutomationPendingStep_orgId_status_resumeAt_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmAutomationPendingStep_tenantId_workflowId_leadId_idx" RENAME TO "CrmAutomationPendingStep_orgId_workflowId_leadId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmAutomationRule_tenantId_isActive_sortOrder_idx" RENAME TO "CrmAutomationRule_orgId_isActive_sortOrder_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmCallDisposition_tenantId_code_key" RENAME TO "CrmCallDisposition_orgId_code_key"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmCallDisposition_tenantId_idx" RENAME TO "CrmCallDisposition_orgId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmCallDisposition_tenantId_name_key" RENAME TO "CrmCallDisposition_orgId_name_key"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmCallLog_tenantId_callSid_key" RENAME TO "CrmCallLog_orgId_callSid_key"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmCallLog_tenantId_idx" RENAME TO "CrmCallLog_orgId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmCallLog_tenantId_leadId_idx" RENAME TO "CrmCallLog_orgId_leadId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmCallLog_tenantId_providerCallSid_createdAt_idx" RENAME TO "CrmCallLog_orgId_providerCallSid_createdAt_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmCampaign_tenantId_idx" RENAME TO "CrmCampaign_orgId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmCompanyProfile_tenantId_key" RENAME TO "CrmCompanyProfile_orgId_key"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmContact_tenantId_accountId_idx" RENAME TO "CrmContact_orgId_accountId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmContact_tenantId_deletedAt_idx" RENAME TO "CrmContact_orgId_deletedAt_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmContact_tenantId_email_idx" RENAME TO "CrmContact_orgId_email_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmContact_tenantId_idx" RENAME TO "CrmContact_orgId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmContact_tenantId_ownerId_idx" RENAME TO "CrmContact_orgId_ownerId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmContact_tenantId_phone_idx" RENAME TO "CrmContact_orgId_phone_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmCtcCallAudit_tenantId_agentUserId_createdAt_idx" RENAME TO "CrmCtcCallAudit_orgId_agentUserId_createdAt_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmCtcCallAudit_tenantId_idx" RENAME TO "CrmCtcCallAudit_orgId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmDashboardPin_tenantId_userId_idx" RENAME TO "CrmDashboardPin_orgId_userId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmDashboardPin_tenantId_userId_reportId_key" RENAME TO "CrmDashboardPin_orgId_userId_reportId_key"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmDocument_tenantId_deletedAt_idx" RENAME TO "CrmDocument_orgId_deletedAt_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmDocument_tenantId_refType_refId_idx" RENAME TO "CrmDocument_orgId_refType_refId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmDocumentFolder_tenantId_deletedAt_idx" RENAME TO "CrmDocumentFolder_orgId_deletedAt_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmDocumentFolder_tenantId_idx" RENAME TO "CrmDocumentFolder_orgId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmDocumentFolder_tenantId_parentFolderId_idx" RENAME TO "CrmDocumentFolder_orgId_parentFolderId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmDocumentFolder_tenantId_refType_refId_idx" RENAME TO "CrmDocumentFolder_orgId_refType_refId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmDocumentLink_tenantId_deletedAt_idx" RENAME TO "CrmDocumentLink_orgId_deletedAt_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmDocumentLink_tenantId_refType_refId_idx" RENAME TO "CrmDocumentLink_orgId_refType_refId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmDocumentLink_tenantId_sourceDocumentId_idx" RENAME TO "CrmDocumentLink_orgId_sourceDocumentId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmDocumentLink_tenantId_targetFolderId_idx" RENAME TO "CrmDocumentLink_orgId_targetFolderId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmFieldValue_tenantId_fieldKey_valueDatetime_idx" RENAME TO "CrmFieldValue_orgId_fieldKey_valueDatetime_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmFieldValue_tenantId_fieldKey_valueNumber_idx" RENAME TO "CrmFieldValue_orgId_fieldKey_valueNumber_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmFieldValue_tenantId_fieldKey_valueText_idx" RENAME TO "CrmFieldValue_orgId_fieldKey_valueText_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmFileAttachment_tenantId_activityId_idx" RENAME TO "CrmFileAttachment_orgId_activityId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmFormDefinition_tenantId_idx" RENAME TO "CrmFormDefinition_orgId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmFormSet_tenantId_surface_isDefault_idx" RENAME TO "CrmFormSet_orgId_surface_isDefault_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmFormSet_tenantId_surface_name_key" RENAME TO "CrmFormSet_orgId_surface_name_key"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmIndiaVoiceWebhookLog_tenantId_callSid_idx" RENAME TO "CrmIndiaVoiceWebhookLog_orgId_callSid_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmIndiaVoiceWebhookLog_tenantId_campid_idx" RENAME TO "CrmIndiaVoiceWebhookLog_orgId_campid_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmIndiaVoiceWebhookLog_tenantId_idx" RENAME TO "CrmIndiaVoiceWebhookLog_orgId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmIndiaVoiceWebhookLog_tenantId_processDedupeKey_key" RENAME TO "CrmIndiaVoiceWebhookLog_orgId_processDedupeKey_key"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmIntegrationConfig_tenantId_name_key" RENAME TO "CrmIntegrationConfig_orgId_name_key"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmIntegrationConfig_tenantId_status_idx" RENAME TO "CrmIntegrationConfig_orgId_status_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmInvoice_tenantId_accountId_idx" RENAME TO "CrmInvoice_orgId_accountId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmInvoice_tenantId_invoiceNumber_key" RENAME TO "CrmInvoice_orgId_invoiceNumber_key"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmInvoice_tenantId_status_idx" RENAME TO "CrmInvoice_orgId_status_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmLandingPage_tenantId_idx" RENAME TO "CrmLandingPage_orgId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmLandingPage_tenantId_slug_key" RENAME TO "CrmLandingPage_orgId_slug_key"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmLead_tenantId_accountId_idx" RENAME TO "CrmLead_orgId_accountId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmLead_tenantId_deletedAt_idx" RENAME TO "CrmLead_orgId_deletedAt_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmLead_tenantId_idx" RENAME TO "CrmLead_orgId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmLead_tenantId_isStarred_idx" RENAME TO "CrmLead_orgId_isStarred_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmLead_tenantId_ownerId_idx" RENAME TO "CrmLead_orgId_ownerId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmLead_tenantId_sourceSystem_externalId_key" RENAME TO "CrmLead_orgId_sourceSystem_externalId_key"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmLead_tenantId_stage_idx" RENAME TO "CrmLead_orgId_stage_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmLeadAttachment_tenantId_leadId_idx" RENAME TO "CrmLeadAttachment_orgId_leadId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmLeadImportJob_tenantId_batchId_idx" RENAME TO "CrmLeadImportJob_orgId_batchId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmLeadImportJob_tenantId_entityType_sourceSystem_idempoten_key" RENAME TO "CrmLeadImportJob_orgId_entityType_sourceSystem_idempotencyK_key"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmLeadImportJob_tenantId_entityType_status_nextRetryAt_idx" RENAME TO "CrmLeadImportJob_orgId_entityType_status_nextRetryAt_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmLeadImportJob_tenantId_idx" RENAME TO "CrmLeadImportJob_orgId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmLeadImportJob_tenantId_status_idx" RENAME TO "CrmLeadImportJob_orgId_status_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmLeadListView_tenantId_userId_idx" RENAME TO "CrmLeadListView_orgId_userId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmLeadSavedList_tenantId_userId_idx" RENAME TO "CrmLeadSavedList_orgId_userId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmLeadSource_tenantId_active_idx" RENAME TO "CrmLeadSource_orgId_active_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmLeadSource_tenantId_idx" RENAME TO "CrmLeadSource_orgId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmLeadSource_tenantId_name_key" RENAME TO "CrmLeadSource_orgId_name_key"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmNote_tenantId_relatedKind_relatedObjectId_idx" RENAME TO "CrmNote_orgId_relatedKind_relatedObjectId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmNotification_tenantId_userId_readAt_idx" RENAME TO "CrmNotification_orgId_userId_readAt_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmOpportunity_tenantId_accountId_idx" RENAME TO "CrmOpportunity_orgId_accountId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmOpportunity_tenantId_deletedAt_idx" RENAME TO "CrmOpportunity_orgId_deletedAt_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmOpportunity_tenantId_idx" RENAME TO "CrmOpportunity_orgId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmOpportunity_tenantId_ownerId_idx" RENAME TO "CrmOpportunity_orgId_ownerId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmOpportunity_tenantId_priceListId_idx" RENAME TO "CrmOpportunity_orgId_priceListId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmOpportunity_tenantId_stage_idx" RENAME TO "CrmOpportunity_orgId_stage_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmOpportunityClientMeeting_tenantId_opportunityId_idx" RENAME TO "CrmOpportunityClientMeeting_orgId_opportunityId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmOpportunityProduct_tenantId_opportunityId_idx" RENAME TO "CrmOpportunityProduct_orgId_opportunityId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmOpportunityStageTransition_tenantId_opportunityId_occurr_idx" RENAME TO "CrmOpportunityStageTransition_orgId_opportunityId_occurredA_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmOrder_tenantId_accountId_idx" RENAME TO "CrmOrder_orgId_accountId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmOrder_tenantId_deletedAt_idx" RENAME TO "CrmOrder_orgId_deletedAt_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmOrder_tenantId_idx" RENAME TO "CrmOrder_orgId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmOrder_tenantId_orderNumber_key" RENAME TO "CrmOrder_orgId_orderNumber_key"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmOrder_tenantId_status_idx" RENAME TO "CrmOrder_orgId_status_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmOrderLine_tenantId_orderId_idx" RENAME TO "CrmOrderLine_orgId_orderId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmOrgWorkspaceSettings_tenantId_key" RENAME TO "CrmOrgWorkspaceSettings_orgId_key"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmOutboundMessageLog_tenantId_idx" RENAME TO "CrmOutboundMessageLog_orgId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmPaymentVerification_tenantId_status_idx" RENAME TO "CrmPaymentVerification_orgId_status_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmPermissionTemplate_tenantId_idx" RENAME TO "CrmPermissionTemplate_orgId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmPermissionTemplate_tenantId_name_key" RENAME TO "CrmPermissionTemplate_orgId_name_key"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmPriceList_tenantId_customerTier_idx" RENAME TO "CrmPriceList_orgId_customerTier_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmPriceList_tenantId_deletedAt_idx" RENAME TO "CrmPriceList_orgId_deletedAt_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmPriceList_tenantId_idx" RENAME TO "CrmPriceList_orgId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmPriceList_tenantId_isActive_idx" RENAME TO "CrmPriceList_orgId_isActive_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmPriceList_tenantId_regionCode_idx" RENAME TO "CrmPriceList_orgId_regionCode_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmPriceListAuditLog_tenantId_priceListId_createdAt_idx" RENAME TO "CrmPriceListAuditLog_orgId_priceListId_createdAt_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmPriceListItem_tenantId_priceListId_deletedAt_idx" RENAME TO "CrmPriceListItem_orgId_priceListId_deletedAt_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmPriceListItem_tenantId_priceListId_idx" RENAME TO "CrmPriceListItem_orgId_priceListId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmPriceListItem_tenantId_productId_idx" RENAME TO "CrmPriceListItem_orgId_productId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmProcessDefinition_tenantId_idx" RENAME TO "CrmProcessDefinition_orgId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmProduct_tenantId_barcode_idx" RENAME TO "CrmProduct_orgId_barcode_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmProduct_tenantId_brandId_idx" RENAME TO "CrmProduct_orgId_brandId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmProduct_tenantId_categoryId_idx" RENAME TO "CrmProduct_orgId_categoryId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmProduct_tenantId_deletedAt_idx" RENAME TO "CrmProduct_orgId_deletedAt_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmProduct_tenantId_idx" RENAME TO "CrmProduct_orgId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmProduct_tenantId_isActive_idx" RENAME TO "CrmProduct_orgId_isActive_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmProduct_tenantId_sku_key" RENAME TO "CrmProduct_orgId_sku_key"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmProductImage_tenantId_productId_idx" RENAME TO "CrmProductImage_orgId_productId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmProductInventory_tenantId_productId_idx" RENAME TO "CrmProductInventory_orgId_productId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmProductInventory_tenantId_productId_variantId_warehouseI_key" RENAME TO "CrmProductInventory_orgId_productId_variantId_warehouseId_key"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmProductInventory_tenantId_warehouseId_idx" RENAME TO "CrmProductInventory_orgId_warehouseId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmProductTaxonomy_tenantId_kind_idx" RENAME TO "CrmProductTaxonomy_orgId_kind_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmProductTaxonomy_tenantId_kind_name_parentId_key" RENAME TO "CrmProductTaxonomy_orgId_kind_name_parentId_key"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmProductTaxonomy_tenantId_parentId_idx" RENAME TO "CrmProductTaxonomy_orgId_parentId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmProductVariant_tenantId_productId_idx" RENAME TO "CrmProductVariant_orgId_productId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmProductVariant_tenantId_sku_key" RENAME TO "CrmProductVariant_orgId_sku_key"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmQuickFilter_tenantId_userId_module_idx" RENAME TO "CrmQuickFilter_orgId_userId_module_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmQuote_tenantId_accountId_idx" RENAME TO "CrmQuote_orgId_accountId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmQuote_tenantId_approvalStatus_idx" RENAME TO "CrmQuote_orgId_approvalStatus_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmQuote_tenantId_deletedAt_idx" RENAME TO "CrmQuote_orgId_deletedAt_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmQuote_tenantId_idx" RENAME TO "CrmQuote_orgId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmQuote_tenantId_opportunityId_idx" RENAME TO "CrmQuote_orgId_opportunityId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmQuote_tenantId_ownerId_idx" RENAME TO "CrmQuote_orgId_ownerId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmQuote_tenantId_parentQuoteId_idx" RENAME TO "CrmQuote_orgId_parentQuoteId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmQuote_tenantId_portalTokenHash_key" RENAME TO "CrmQuote_orgId_portalTokenHash_key"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmQuote_tenantId_quoteNumber_key" RENAME TO "CrmQuote_orgId_quoteNumber_key"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmQuote_tenantId_status_idx" RENAME TO "CrmQuote_orgId_status_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmQuoteApproval_tenantId_quoteId_idx" RENAME TO "CrmQuoteApproval_orgId_quoteId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmQuoteApproval_tenantId_status_idx" RENAME TO "CrmQuoteApproval_orgId_status_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmQuoteComment_tenantId_quoteId_createdAt_idx" RENAME TO "CrmQuoteComment_orgId_quoteId_createdAt_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmQuoteEngagementEvent_tenantId_eventType_idx" RENAME TO "CrmQuoteEngagementEvent_orgId_eventType_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmQuoteEngagementEvent_tenantId_quoteId_createdAt_idx" RENAME TO "CrmQuoteEngagementEvent_orgId_quoteId_createdAt_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmQuoteLine_tenantId_quoteId_idx" RENAME TO "CrmQuoteLine_orgId_quoteId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmQuotePdfSnapshot_tenantId_quoteId_createdAt_idx" RENAME TO "CrmQuotePdfSnapshot_orgId_quoteId_createdAt_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmQuotePortalAccess_tenantId_quoteId_idx" RENAME TO "CrmQuotePortalAccess_orgId_quoteId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmQuoteStatusTransition_tenantId_quoteId_idx" RENAME TO "CrmQuoteStatusTransition_orgId_quoteId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmQuoteTemplate_tenantId_isActive_idx" RENAME TO "CrmQuoteTemplate_orgId_isActive_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmQuoteTemplate_tenantId_key_key" RENAME TO "CrmQuoteTemplate_orgId_key_key"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmReportDefinition_tenantId_idx" RENAME TO "CrmReportDefinition_orgId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmSalesGroup_tenantId_idx" RENAME TO "CrmSalesGroup_orgId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmSalesGroup_tenantId_name_key" RENAME TO "CrmSalesGroup_orgId_name_key"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmSalesTeam_tenantId_idx" RENAME TO "CrmSalesTeam_orgId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmSalesTeam_tenantId_name_key" RENAME TO "CrmSalesTeam_orgId_name_key"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmSequence_tenantId_name_key" RENAME TO "CrmSequence_orgId_name_key"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmSetSelectionLog_tenantId_leadId_idx" RENAME TO "CrmSetSelectionLog_orgId_leadId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmSetSelectionLog_tenantId_wasOverridden_idx" RENAME TO "CrmSetSelectionLog_orgId_wasOverridden_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmSlaLeadTracking_tenantId_leadId_idx" RENAME TO "CrmSlaLeadTracking_orgId_leadId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmSlaLeadTracking_tenantId_status_idx" RENAME TO "CrmSlaLeadTracking_orgId_status_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmSlaRule_tenantId_idx" RENAME TO "CrmSlaRule_orgId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmSlaRule_tenantId_sourceSystem_externalId_key" RENAME TO "CrmSlaRule_orgId_sourceSystem_externalId_key"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmStockMovement_tenantId_productId_createdAt_idx" RENAME TO "CrmStockMovement_orgId_productId_createdAt_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmStockMovement_tenantId_warehouseId_idx" RENAME TO "CrmStockMovement_orgId_warehouseId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmTask_tenantId_assignedToUserId_idx" RENAME TO "CrmTask_orgId_assignedToUserId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmTask_tenantId_idx" RENAME TO "CrmTask_orgId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmTask_tenantId_status_idx" RENAME TO "CrmTask_orgId_status_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmTelephonyProvider_tenantId_idx" RENAME TO "CrmTelephonyProvider_orgId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmVirtualNumber_tenantId_idx" RENAME TO "CrmVirtualNumber_orgId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmVirtualNumber_tenantId_number_key" RENAME TO "CrmVirtualNumber_orgId_number_key"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmWarehouse_tenantId_code_key" RENAME TO "CrmWarehouse_orgId_code_key"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmWarehouse_tenantId_idx" RENAME TO "CrmWarehouse_orgId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmWebWidget_tenantId_idx" RENAME TO "CrmWebWidget_orgId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmWorkflowDefinition_tenantId_deletedAt_idx" RENAME TO "CrmWorkflowDefinition_orgId_deletedAt_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmWorkflowDefinition_tenantId_idx" RENAME TO "CrmWorkflowDefinition_orgId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmWorkflowDefinition_tenantId_sourceSystem_externalId_key" RENAME TO "CrmWorkflowDefinition_orgId_sourceSystem_externalId_key"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."CrmWorkflowDefinition_tenantId_status_idx" RENAME TO "CrmWorkflowDefinition_orgId_status_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."LeadSquaredSyncMap_tenantId_idx" RENAME TO "LeadSquaredSyncMap_orgId_idx"$stmt$;
    EXECUTE $stmt$ALTER INDEX "app_quikcrmexpress"."LeadSquaredSyncMap_tenantId_lsqProspectId_key" RENAME TO "LeadSquaredSyncMap_orgId_lsqProspectId_key"$stmt$;
  END IF;
END
$guard$;
