/**
 * PHASE 22 — Scheduling (`/api/scheduling/*`), all 9 routes.
 *
 *   POST   /api/scheduling/classes/generate            (TENANT_ADMIN|SUB_ADMIN)
 *   GET    /api/scheduling/classes/[id]                (any authed — requireAuth only)
 *   PATCH  /api/scheduling/classes/[id]/start          (TEACHER|TENANT_ADMIN|SUB_ADMIN)
 *   PATCH  /api/scheduling/classes/[id]/complete       (TEACHER|TENANT_ADMIN|SUB_ADMIN)
 *   PATCH  /api/scheduling/classes/[id]/cancel         (TEACHER|TENANT_ADMIN|SUB_ADMIN)
 *   PATCH  /api/scheduling/classes/[id]/reschedule     (TEACHER|TENANT_ADMIN|SUB_ADMIN)
 *   GET    /api/scheduling/student/classes             (LEARNER|PARENT|TENANT_ADMIN|SUB_ADMIN)
 *   GET    /api/scheduling/teacher/classes             (TEACHER|TENANT_ADMIN|SUB_ADMIN)
 *   GET    /api/scheduling/admin/session-join-timestamps (TENANT_ADMIN|SUB_ADMIN)
 *
 * Authorization angles specific to this domain:
 *  - `GET /api/scheduling/classes/[id]` is `requireAuth` with no role guard and
 *    no batch-membership check (app/api/scheduling/classes/[id]/route.ts:6-8);
 *  - `/student/classes` lets a PARENT or admin name ANY `studentId`
 *    (app/api/scheduling/student/classes/route.ts:15-17) with no parent↔child
 *    link check — the F-011 pattern. The seeded PARENT has no child link at
 *    all, so a 200 with another student's timetable is the F-010 defect class;
 *  - the four state-change routes admit any TEACHER, not just the class's own
 *    teacher (`startClass` etc. filter on `orgId` alone,
 *    scheduling-service.ts:302-304 / 349-351 / 366-368 / 389-390).
 *
 * Fixture strategy: every mutation runs against classes GENERATED by this
 * phase in a far-future window, never against the seeded `scheduledClassId`,
 * so re-runs are idempotent and the manifest stays valid.
 */

import { test, expect, type APIRequestContext } from "@playwright/test";
import { apiAs, safeJson } from "../fixtures/api";
import { loadManifest } from "../fixtures/auth";

const m = loadManifest();
const MISSING = "00000000-0000-0000-0000-000000000000";
const RUN = `AUDIT22-${Date.now()}`;

const CEIL = 60_000;
const GET = (a: APIRequestContext, p: string) => a.get(p, { timeout: CEIL });
const POST = (a: APIRequestContext, p: string, data?: unknown) =>
  a.post(p, { timeout: CEIL, ...(data !== undefined ? { data } : {}) });
const PATCH = (a: APIRequestContext, p: string, data?: unknown) =>
  a.patch(p, { timeout: CEIL, ...(data !== undefined ? { data } : {}) });

interface ScheduledClass {
  id: string;
  title: string;
  status: string;
  startTime: string;
  endTime: string;
  cancellationReason?: string | null;
  rescheduledTo?: string | null;
  batchId: string | { _id: string };
  teacherId: string | { _id: string };
}

/** Classes generated for this run, consumed one per mutation test. */
let pool: ScheduledClass[] = [];
let poolIdx = 0;
const takeClass = (): ScheduledClass => {
  const c = pool[poolIdx++];
  expect(c, "ran out of generated classes — widen the generate window").toBeTruthy();
  return c;
};

test.beforeAll(async () => {
  test.setTimeout(180_000); // rule 9
  expect(m.batchId, "seed manifest has no batchId — reseed before running").toBeTruthy();

  const admin = await apiAs("tenantAdmin", { timeout: CEIL });

  // Put the seeded learner in the seeded batch so /student/classes has data to
  // return. Idempotent — the service de-duplicates.
  await POST(admin, `/api/batches/${m.batchId}/students`, { studentIds: [m.users.learner.userId] });

  // Generate over a 3-week window inside the batch's own start/end range.
  // `generateClasses` skips slots that already have a non-cancelled class, so
  // repeated runs top the pool up rather than duplicating it.
  const from = new Date();
  from.setDate(from.getDate() + 7);
  const to = new Date(from);
  to.setDate(to.getDate() + 21);
  const gen = await POST(admin, "/api/scheduling/classes/generate", {
    batchId: m.batchId,
    fromDate: from.toISOString().slice(0, 10),
    toDate: to.toISOString().slice(0, 10),
  });
  expect(gen.status(), `generate said ${await gen.text()}`).toBe(200);

  // Take the pool from the teacher's own list, filtered to future scheduled
  // classes only — the seeded class is in the past and already has a meeting.
  const list = await GET(admin, "/api/scheduling/teacher/classes");
  const all = (await safeJson(list)) as ScheduledClass[];
  pool = all
    .filter((c) => c.status === "scheduled" && new Date(c.startTime) > new Date() && c.id !== m.scheduledClassId)
    .sort((a, b) => +new Date(a.startTime) - +new Date(b.startTime));
  expect(pool.length, "no generated classes available to mutate").toBeGreaterThanOrEqual(4);

  await admin.dispose();
});

test.describe("Phase 22 — scheduling: reads", () => {
  test("GET /api/scheduling/classes/[id] returns the documented shape", async () => {
    const api = await apiAs("tenantAdmin", { timeout: CEIL });
    const res = await GET(api, `/api/scheduling/classes/${m.scheduledClassId}`);
    expect(res.status()).toBe(200);
    const c = (await safeJson(res)) as ScheduledClass;
    expect(c.id).toBe(m.scheduledClassId);
    expect(c.startTime).toBeTruthy();
    expect(typeof c.status).toBe("string");
    await api.dispose();
  });

  test("GET /api/scheduling/classes/[id] with a nonexistent id is 404, not 500", async () => {
    const api = await apiAs("tenantAdmin", { timeout: CEIL });
    const res = await GET(api, `/api/scheduling/classes/${MISSING}`);
    expect(res.status()).toBe(404);
    expect(((await safeJson(res)) as { success?: boolean }).success).toBe(false);
    await api.dispose();
  });

  test("GET /api/scheduling/teacher/classes returns the teacher's own timetable", async () => {
    const api = await apiAs("teacher", { timeout: CEIL });
    const res = await GET(api, "/api/scheduling/teacher/classes");
    expect(res.status()).toBe(200);
    const rows = (await safeJson(res)) as ScheduledClass[];
    expect(Array.isArray(rows)).toBe(true);
    expect(rows.length).toBeGreaterThan(0);
    await api.dispose();
  });

  test("GET /api/scheduling/student/classes returns the learner's own timetable", async () => {
    const api = await apiAs("learner", { timeout: CEIL });
    const res = await GET(api, "/api/scheduling/student/classes");
    expect(res.status()).toBe(200);
    const rows = (await safeJson(res)) as ScheduledClass[];
    expect(Array.isArray(rows)).toBe(true);
    expect(rows.length, "learner was added to the seeded batch in beforeAll").toBeGreaterThan(0);
    await api.dispose();
  });

  test("GET /api/scheduling/admin/session-join-timestamps returns join telemetry", async () => {
    const api = await apiAs("tenantAdmin", { timeout: CEIL });
    const res = await GET(api, "/api/scheduling/admin/session-join-timestamps");
    expect(res.status()).toBe(200);
    const rows = (await safeJson(res)) as Array<{ scheduledClassId: string; students: unknown[] }>;
    expect(Array.isArray(rows)).toBe(true);
    if (rows.length) {
      expect(rows[0]).toHaveProperty("scheduledClassId");
      expect(rows[0]).toHaveProperty("teacherFirstJoinAt");
    }
    await api.dispose();
  });

  test("a learner's own timetable ignores a spoofed ?studentId", async () => {
    // The route only honours `studentId` for PARENT/admin
    // (app/api/scheduling/student/classes/route.ts:15-17); a LEARNER is pinned
    // to `actor.id`. Confirm the pin holds.
    const api = await apiAs("learner", { timeout: CEIL });
    const res = await GET(api, `/api/scheduling/student/classes?studentId=${m.users.teacher.userId}`);
    expect(res.status()).toBe(200);
    const spoofed = (await safeJson(res)) as ScheduledClass[];
    const own = (await safeJson(await GET(api, "/api/scheduling/student/classes"))) as ScheduledClass[];
    expect(spoofed.length, "?studentId changed a LEARNER's result set").toBe(own.length);
    await api.dispose();
  });
});

test.describe("Phase 22 — scheduling: role gating", () => {
  const DENIED: Array<[string, "learner" | "parent" | "teacher" | "manager", string]> = [
    ["GET /api/scheduling/admin/session-join-timestamps", "teacher", "/api/scheduling/admin/session-join-timestamps"],
    ["GET /api/scheduling/admin/session-join-timestamps", "learner", "/api/scheduling/admin/session-join-timestamps"],
    ["GET /api/scheduling/teacher/classes", "learner", "/api/scheduling/teacher/classes"],
    ["GET /api/scheduling/student/classes", "teacher", "/api/scheduling/student/classes"],
    ["GET /api/scheduling/student/classes", "manager", "/api/scheduling/student/classes"],
  ];

  for (const [label, role, path] of DENIED) {
    test(`${role} is refused ${label}`, async () => {
      const api = await apiAs(role, { timeout: CEIL });
      const res = await GET(api, path);
      expect(res.status(), `${role} reached ${label}`).toBe(403);
      await api.dispose();
    });
  }

  test("LEARNER cannot generate classes", async () => {
    const api = await apiAs("learner", { timeout: CEIL });
    const res = await POST(api, "/api/scheduling/classes/generate", { batchId: m.batchId });
    expect(res.status()).toBe(403);
    await api.dispose();
  });

  test("TEACHER cannot generate classes (admin-only)", async () => {
    const api = await apiAs("teacher", { timeout: CEIL });
    const res = await POST(api, "/api/scheduling/classes/generate", { batchId: m.batchId });
    expect(res.status()).toBe(403);
    await api.dispose();
  });

  test("LEARNER cannot start, complete, cancel or reschedule a class", async () => {
    test.setTimeout(120_000);
    const api = await apiAs("learner", { timeout: CEIL });
    const id = m.scheduledClassId;
    const probes: Array<[string, () => Promise<{ status(): number }>]> = [
      ["start", () => PATCH(api, `/api/scheduling/classes/${id}/start`)],
      ["complete", () => PATCH(api, `/api/scheduling/classes/${id}/complete`)],
      ["cancel", () => PATCH(api, `/api/scheduling/classes/${id}/cancel`, { reason: RUN })],
      [
        "reschedule",
        () =>
          PATCH(api, `/api/scheduling/classes/${id}/reschedule`, {
            newStartTime: new Date(Date.now() + 9e8).toISOString(),
            newEndTime: new Date(Date.now() + 9e8 + 36e5).toISOString(),
            reason: RUN,
          }),
      ],
    ];
    for (const [label, run] of probes) {
      const res = await run();
      expect(res.status(), `LEARNER reached ${label}`).toBe(403);
    }
    await api.dispose();
  });
});

test.describe("Phase 22 — scheduling: state machine (each mutation read back)", () => {
  test("start then complete, verified by read-back", async () => {
    test.setTimeout(120_000);
    const admin = await apiAs("tenantAdmin", { timeout: CEIL });
    const cls = takeClass();

    const started = await PATCH(admin, `/api/scheduling/classes/${cls.id}/start`);
    expect(started.status(), `start said ${await started.text()}`).toBe(200);
    const afterStart = (await safeJson(await GET(admin, `/api/scheduling/classes/${cls.id}`))) as ScheduledClass;
    expect(afterStart.status, "start did not persist").toBe("in_progress");

    const done = await PATCH(admin, `/api/scheduling/classes/${cls.id}/complete`);
    expect(done.status()).toBe(200);
    const afterDone = (await safeJson(await GET(admin, `/api/scheduling/classes/${cls.id}`))) as ScheduledClass;
    expect(afterDone.status, "complete did not persist").toBe("completed");

    // The state machine refuses to re-start a completed class
    // (scheduling-service.ts:305).
    const again = await PATCH(admin, `/api/scheduling/classes/${cls.id}/start`);
    expect(again.status(), "a completed class must not be startable").toBe(400);

    await admin.dispose();
  });

  test("cancel records the reason, verified by read-back", async () => {
    test.setTimeout(120_000);
    const teacher = await apiAs("teacher", { timeout: CEIL });
    const cls = takeClass();

    const res = await PATCH(teacher, `/api/scheduling/classes/${cls.id}/cancel`, { reason: `${RUN} cancelled` });
    expect(res.status(), `cancel said ${await res.text()}`).toBe(200);

    const after = (await safeJson(await GET(teacher, `/api/scheduling/classes/${cls.id}`))) as ScheduledClass;
    expect(after.status).toBe("cancelled");
    expect(after.cancellationReason).toBe(`${RUN} cancelled`);

    // A cancelled class cannot then be rescheduled (scheduling-service.ts:391).
    const resched = await PATCH(teacher, `/api/scheduling/classes/${cls.id}/reschedule`, {
      newStartTime: new Date(Date.now() + 9e8).toISOString(),
      newEndTime: new Date(Date.now() + 9e8 + 36e5).toISOString(),
      reason: RUN,
    });
    expect(resched.status(), "a cancelled class must not be reschedulable").toBe(400);
    await teacher.dispose();
  });

  test("reschedule creates a successor and marks the original, verified by read-back", async () => {
    test.setTimeout(120_000);
    const teacher = await apiAs("teacher", { timeout: CEIL });
    const cls = takeClass();

    const newStart = new Date(new Date(cls.startTime).getTime() + 2 * 864e5);
    const newEnd = new Date(newStart.getTime() + 36e5);
    const res = await PATCH(teacher, `/api/scheduling/classes/${cls.id}/reschedule`, {
      newStartTime: newStart.toISOString(),
      newEndTime: newEnd.toISOString(),
      reason: `${RUN} moved`,
      newLocation: "Room AUDIT22",
    });
    expect(res.status(), `reschedule said ${await res.text()}`).toBe(200);

    const original = (await safeJson(await GET(teacher, `/api/scheduling/classes/${cls.id}`))) as ScheduledClass;
    expect(original.status, "original not marked rescheduled").toBe("rescheduled");
    expect(original.rescheduledTo, "no successor id recorded").toBeTruthy();

    const successor = (await safeJson(
      await GET(teacher, `/api/scheduling/classes/${original.rescheduledTo}`),
    )) as ScheduledClass;
    expect(successor.status).toBe("scheduled");
    expect(new Date(successor.startTime).toISOString()).toBe(newStart.toISOString());
    await teacher.dispose();
  });

  test("state changes against a nonexistent class id are 404, not 500", async () => {
    test.setTimeout(120_000);
    const admin = await apiAs("tenantAdmin", { timeout: CEIL });
    const probes: Array<[string, () => Promise<{ status(): number }>]> = [
      ["start", () => PATCH(admin, `/api/scheduling/classes/${MISSING}/start`)],
      ["complete", () => PATCH(admin, `/api/scheduling/classes/${MISSING}/complete`)],
      ["cancel", () => PATCH(admin, `/api/scheduling/classes/${MISSING}/cancel`, { reason: RUN })],
      [
        "reschedule",
        () =>
          PATCH(admin, `/api/scheduling/classes/${MISSING}/reschedule`, {
            newStartTime: new Date(Date.now() + 9e8).toISOString(),
            newEndTime: new Date(Date.now() + 9e8 + 36e5).toISOString(),
            reason: RUN,
          }),
      ],
    ];
    for (const [label, run] of probes) {
      const res = await run();
      expect(res.status(), `${label} returned ${res.status()} for a missing id`).toBe(404);
    }
    await admin.dispose();
  });

  test("generate against a nonexistent batch id is 404, not 500", async () => {
    const admin = await apiAs("tenantAdmin", { timeout: CEIL });
    const res = await POST(admin, "/api/scheduling/classes/generate", { batchId: MISSING });
    expect(res.status()).toBe(404);
    await admin.dispose();
  });
});

test.describe("Phase 22 — scheduling: intra-tenant ownership", () => {
  /**
   * F-010 defect class. `/student/classes` takes `studentId` from the query
   * string whenever the caller is a PARENT, with no check that the named
   * student is that parent's child — the `LmsUserParent` link table is never
   * consulted (app/api/scheduling/student/classes/route.ts:15-17). The seeded
   * PARENT has NO child link at all, so any non-empty result is proof.
   */
  test("PARENT with no child link reads an unrelated learner's timetable", async () => {
    const parent = await apiAs("parent", { timeout: CEIL });
    const res = await GET(parent, `/api/scheduling/student/classes?studentId=${m.users.learner.userId}`);
    const rows = (await safeJson(res)) as ScheduledClass[];
    console.log(
      `[F-P22] PARENT -> /student/classes?studentId={learner}: ${res.status()}, ${
        Array.isArray(rows) ? rows.length : "?"
      } row(s)`,
    );
    expect(
      res.status() === 403 || (Array.isArray(rows) && rows.length === 0),
      `OWNERSHIP: an unlinked PARENT read ${Array.isArray(rows) ? rows.length : "?"} of another ` +
        `learner's scheduled classes. Same defect class as F-010/F-011 — the route trusts the ` +
        `caller-supplied studentId (app/api/scheduling/student/classes/route.ts:15-17) and ` +
        `getStudentClasses filters on {orgId, studentId} only.`,
    ).toBe(true);
    await parent.dispose();
  });

  /**
   * `GET /api/scheduling/classes/[id]` is requireAuth-only. Recorded rather
   * than asserted: the payload is a class title and time, which a school might
   * legitimately treat as tenant-public.
   */
  test("[ownership] any authenticated role can read any class by id", async () => {
    const parent = await apiAs("parent", { timeout: CEIL });
    const res = await GET(parent, `/api/scheduling/classes/${m.scheduledClassId}`);
    const c = (await safeJson(res)) as ScheduledClass;
    const teacher = typeof c.teacherId === "object" ? (c.teacherId as { email?: string }) : null;
    console.log(
      `[INFO] PARENT GET /api/scheduling/classes/{id} -> ${res.status()}; teacher email exposed: ${
        teacher?.email ?? "n/a"
      }`,
    );
    expect([200, 403, 404]).toContain(res.status());
    await parent.dispose();
  });
});
