/**
 * Storage Driver Interface
 *
 * One concrete driver — Google Cloud Storage (see gcs-driver.ts). Routes and
 * services only see `StorageDriver`, never the concrete backend.
 *
 * Design notes:
 *  - Presigned URLs are the default upload path. The browser PUTs the file
 *    directly to the object store, then POSTs `/api/files/confirm` to flip
 *    the metadata row from "pending_upload" → "active". This keeps large
 *    files off the Next.js lambda and avoids the 4.5 MB body-parser limit.
 *  - `putObject` exists for server-side uploads (BOQ imports parsed
 *    server-side, PDFs generated by the backend, etc.).
 *  - Presigned download URLs are short-lived (default 5 min).
 */

export interface PresignedUploadUrl {
  method: "PUT";
  url: string;
  headers: Record<string, string>;
  /** Seconds until the presigned URL expires. */
  expiresIn: number;
}

export interface PresignedDownloadUrl {
  url: string;
  expiresIn: number;
}

export interface StorageDriver {
  readonly kind: "s3" | "gcs";
  readonly bucket: string;

  /** Generate a presigned URL the browser can PUT the file body to. */
  getPresignedUploadUrl(params: {
    key: string;
    contentType: string;
    contentLength: number;
    expiresIn?: number;
  }): Promise<PresignedUploadUrl>;

  /** Generate a short-lived download URL. */
  getPresignedDownloadUrl(params: {
    key: string;
    fileName?: string;
    expiresIn?: number;
  }): Promise<PresignedDownloadUrl>;

  /** Server-side upload of an in-memory buffer. */
  putObject(params: {
    key: string;
    body: Buffer | Uint8Array;
    contentType: string;
  }): Promise<void>;

  /** Read the object HEAD — used by upload-confirm to verify size and checksum. */
  headObject(key: string): Promise<{
    exists: boolean;
    contentLength?: number;
    contentType?: string;
    etag?: string;
  }>;

  /** Hard delete. Callers should almost always prefer soft-delete on the metadata row. */
  deleteObject(key: string): Promise<void>;
}

// ─── Driver factory ─────────────────────────────────────────────────
// Kept in a separate file to avoid circular imports — see ./index.ts.
