-- Rename the tenantId scope column to orgId across all LMS tables (quikscale parity).
-- Data preserved (RENAME, not drop/add). Values already hold platform orgId.
ALTER TABLE "academic_calendars" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "activity_logs" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "analytics_cache" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "analytics_events" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "assessments" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "attendance" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "batches" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "bookmarks" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "call_escalations" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "certificate_selected_tenants" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "certificates" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "certificates_issued" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "consent_records" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "conversations" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "counters" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "course_assignments" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "course_selected_tenants" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "courses" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "credit_packages" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "credit_transactions" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "discussions" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "exam_sessions" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "exams" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "grade_records" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "groups" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "homework" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "homework_submissions" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "incident_reports" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "master_course_selected_tenants" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "meetings" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "modules" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "non_teaching_tasks" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "privacy_audit_logs" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "proctoring_logs" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "progress" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "questions" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "quiz_attempts" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "quiz_incident_reports" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "quiz_proctoring_logs" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "quiz_proctoring_sessions" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "scheduled_classes" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "sections" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "shared_content" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "student_reminder_calls" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "subjects" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "teacher_lateness_reminder_logs" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "teacher_levels" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "teacher_payouts" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "tenant_logs" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "tutoring_requests" RENAME COLUMN "tenantId" TO "orgId";
ALTER TABLE "users" RENAME COLUMN "tenantId" TO "orgId";
ALTER INDEX "academic_calendars_tenantId_academicYear_key" RENAME TO "academic_calendars_orgId_academicYear_key";
ALTER INDEX "academic_calendars_tenantId_idx" RENAME TO "academic_calendars_orgId_idx";
ALTER INDEX "activity_logs_tenantId_timestamp_idx" RENAME TO "activity_logs_orgId_timestamp_idx";
ALTER INDEX "analytics_cache_tenantId_metricKey_idx" RENAME TO "analytics_cache_orgId_metricKey_idx";
ALTER INDEX "analytics_events_tenantId_eventType_createdAt_idx" RENAME TO "analytics_events_orgId_eventType_createdAt_idx";
ALTER INDEX "assessments_tenantId_moduleId_idx" RENAME TO "assessments_orgId_moduleId_idx";
ALTER INDEX "attendance_tenantId_batchId_classDate_idx" RENAME TO "attendance_orgId_batchId_classDate_idx";
ALTER INDEX "attendance_tenantId_scheduledClassId_idx" RENAME TO "attendance_orgId_scheduledClassId_idx";
ALTER INDEX "attendance_tenantId_studentId_classDate_idx" RENAME TO "attendance_orgId_studentId_classDate_idx";
ALTER INDEX "batches_tenantId_academicYear_status_idx" RENAME TO "batches_orgId_academicYear_status_idx";
ALTER INDEX "batches_tenantId_grade_section_subject_idx" RENAME TO "batches_orgId_grade_section_subject_idx";
ALTER INDEX "batches_tenantId_name_academicYear_key" RENAME TO "batches_orgId_name_academicYear_key";
ALTER INDEX "batches_tenantId_teacherId_status_idx" RENAME TO "batches_orgId_teacherId_status_idx";
ALTER INDEX "bookmarks_tenantId_userId_courseId_key" RENAME TO "bookmarks_orgId_userId_courseId_key";
ALTER INDEX "call_escalations_tenantId_scheduledClassId_idx" RENAME TO "call_escalations_orgId_scheduledClassId_idx";
ALTER INDEX "call_escalations_tenantId_teacherId_createdAt_idx" RENAME TO "call_escalations_orgId_teacherId_createdAt_idx";
ALTER INDEX "certificate_selected_tenants_certificateId_tenantId_key" RENAME TO "certificate_selected_tenants_certificateId_orgId_key";
ALTER INDEX "certificate_selected_tenants_tenantId_idx" RENAME TO "certificate_selected_tenants_orgId_idx";
ALTER INDEX "certificates_issued_tenantId_learnerId_courseId_idx" RENAME TO "certificates_issued_orgId_learnerId_courseId_idx";
ALTER INDEX "certificates_issued_tenantId_learnerId_courseId_key" RENAME TO "certificates_issued_orgId_learnerId_courseId_key";
ALTER INDEX "certificates_tenantId_isActive_idx" RENAME TO "certificates_orgId_isActive_idx";
ALTER INDEX "consent_records_tenantId_parentId_idx" RENAME TO "consent_records_orgId_parentId_idx";
ALTER INDEX "consent_records_tenantId_studentId_consentType_idx" RENAME TO "consent_records_orgId_studentId_consentType_idx";
ALTER INDEX "conversations_tenantId_lastMessageAt_idx" RENAME TO "conversations_orgId_lastMessageAt_idx";
ALTER INDEX "counters_tenantId_type_key" RENAME TO "counters_orgId_type_key";
ALTER INDEX "course_assignments_tenantId_courseId_idx" RENAME TO "course_assignments_orgId_courseId_idx";
ALTER INDEX "course_assignments_tenantId_isMandatory_idx" RENAME TO "course_assignments_orgId_isMandatory_idx";
ALTER INDEX "course_assignments_tenantId_targetId_targetType_idx" RENAME TO "course_assignments_orgId_targetId_targetType_idx";
ALTER INDEX "course_selected_tenants_courseId_tenantId_key" RENAME TO "course_selected_tenants_courseId_orgId_key";
ALTER INDEX "course_selected_tenants_tenantId_idx" RENAME TO "course_selected_tenants_orgId_idx";
ALTER INDEX "courses_category_tenantId_idx" RENAME TO "courses_category_orgId_idx";
ALTER INDEX "courses_tenantId_status_idx" RENAME TO "courses_orgId_status_idx";
ALTER INDEX "credit_packages_tenantId_studentId_idx" RENAME TO "credit_packages_orgId_studentId_idx";
ALTER INDEX "credit_transactions_tenantId_studentId_createdAt_idx" RENAME TO "credit_transactions_orgId_studentId_createdAt_idx";
ALTER INDEX "discussions_tenantId_courseId_isDeleted_idx" RENAME TO "discussions_orgId_courseId_isDeleted_idx";
ALTER INDEX "exam_sessions_tenantId_examId_studentId_key" RENAME TO "exam_sessions_orgId_examId_studentId_key";
ALTER INDEX "exams_tenantId_batchId_status_idx" RENAME TO "exams_orgId_batchId_status_idx";
ALTER INDEX "exams_tenantId_status_scheduledStartTime_idx" RENAME TO "exams_orgId_status_scheduledStartTime_idx";
ALTER INDEX "grade_records_tenantId_batchId_overallPercentage_idx" RENAME TO "grade_records_orgId_batchId_overallPercentage_idx";
ALTER INDEX "grade_records_tenantId_studentId_batchId_term_key" RENAME TO "grade_records_orgId_studentId_batchId_term_key";
ALTER INDEX "groups_tenantId_idx" RENAME TO "groups_orgId_idx";
ALTER INDEX "groups_tenantId_name_key" RENAME TO "groups_orgId_name_key";
ALTER INDEX "homework_submissions_tenantId_studentId_submittedAt_idx" RENAME TO "homework_submissions_orgId_studentId_submittedAt_idx";
ALTER INDEX "homework_tenantId_batchId_status_idx" RENAME TO "homework_orgId_batchId_status_idx";
ALTER INDEX "homework_tenantId_teacherId_idx" RENAME TO "homework_orgId_teacherId_idx";
ALTER INDEX "master_course_selected_tenants_masterCourseId_tenantId_key" RENAME TO "master_course_selected_tenants_masterCourseId_orgId_key";
ALTER INDEX "master_course_selected_tenants_tenantId_idx" RENAME TO "master_course_selected_tenants_orgId_idx";
ALTER INDEX "meetings_tenantId_scheduledClassId_idx" RENAME TO "meetings_orgId_scheduledClassId_idx";
ALTER INDEX "meetings_tenantId_status_idx" RENAME TO "meetings_orgId_status_idx";
ALTER INDEX "modules_tenantId_courseId_idx" RENAME TO "modules_orgId_courseId_idx";
ALTER INDEX "non_teaching_tasks_tenantId_status_createdAt_idx" RENAME TO "non_teaching_tasks_orgId_status_createdAt_idx";
ALTER INDEX "non_teaching_tasks_tenantId_teacherId_status_idx" RENAME TO "non_teaching_tasks_orgId_teacherId_status_idx";
ALTER INDEX "privacy_audit_logs_tenantId_createdAt_idx" RENAME TO "privacy_audit_logs_orgId_createdAt_idx";
ALTER INDEX "progress_tenantId_learnerId_courseId_key" RENAME TO "progress_orgId_learnerId_courseId_key";
ALTER INDEX "questions_tenantId_subject_difficulty_idx" RENAME TO "questions_orgId_subject_difficulty_idx";
ALTER INDEX "questions_tenantId_tags_idx" RENAME TO "questions_orgId_tags_idx";
ALTER INDEX "questions_tenantId_type_idx" RENAME TO "questions_orgId_type_idx";
ALTER INDEX "quiz_attempts_tenantId_learnerId_assessmentId_idx" RENAME TO "quiz_attempts_orgId_learnerId_assessmentId_idx";
ALTER INDEX "quiz_attempts_tenantId_learnerId_courseId_idx" RENAME TO "quiz_attempts_orgId_learnerId_courseId_idx";
ALTER INDEX "quiz_proctoring_sessions_tenantId_assessmentId_learnerId_key" RENAME TO "quiz_proctoring_sessions_orgId_assessmentId_learnerId_key";
ALTER INDEX "scheduled_classes_tenantId_batchId_startTime_idx" RENAME TO "scheduled_classes_orgId_batchId_startTime_idx";
ALTER INDEX "scheduled_classes_tenantId_status_startTime_idx" RENAME TO "scheduled_classes_orgId_status_startTime_idx";
ALTER INDEX "scheduled_classes_tenantId_teacherId_startTime_idx" RENAME TO "scheduled_classes_orgId_teacherId_startTime_idx";
ALTER INDEX "sections_tenantId_grade_name_key" RENAME TO "sections_orgId_grade_name_key";
ALTER INDEX "sections_tenantId_idx" RENAME TO "sections_orgId_idx";
ALTER INDEX "shared_content_masterCourseId_tenantId_key" RENAME TO "shared_content_masterCourseId_orgId_key";
ALTER INDEX "shared_content_tenantId_isActive_idx" RENAME TO "shared_content_orgId_isActive_idx";
ALTER INDEX "student_reminder_calls_tenantId_scheduledClassId_studentId_idx" RENAME TO "student_reminder_calls_orgId_scheduledClassId_studentId_idx";
ALTER INDEX "student_reminder_calls_tenantId_studentId_createdAt_idx" RENAME TO "student_reminder_calls_orgId_studentId_createdAt_idx";
ALTER INDEX "subjects_tenantId_idx" RENAME TO "subjects_orgId_idx";
ALTER INDEX "subjects_tenantId_name_key" RENAME TO "subjects_orgId_name_key";
ALTER INDEX "teacher_lateness_reminder_logs_tenantId_batchId_teacherId_key" RENAME TO "teacher_lateness_reminder_logs_orgId_batchId_teacherId_key";
ALTER INDEX "teacher_levels_tenantId_teacherId_key" RENAME TO "teacher_levels_orgId_teacherId_key";
ALTER INDEX "teacher_payouts_tenantId_status_idx" RENAME TO "teacher_payouts_orgId_status_idx";
ALTER INDEX "teacher_payouts_tenantId_teacherId_periodStart_periodEnd_key" RENAME TO "teacher_payouts_orgId_teacherId_periodStart_periodEnd_key";
ALTER INDEX "tenant_logs_tenantId_actionType_createdAt_idx" RENAME TO "tenant_logs_orgId_actionType_createdAt_idx";
ALTER INDEX "tenant_logs_tenantId_createdAt_idx" RENAME TO "tenant_logs_orgId_createdAt_idx";
ALTER INDEX "tutoring_requests_tenantId_studentId_status_idx" RENAME TO "tutoring_requests_orgId_studentId_status_idx";
ALTER INDEX "tutoring_requests_tenantId_teacherId_status_idx" RENAME TO "tutoring_requests_orgId_teacherId_status_idx";
ALTER INDEX "users_tenantId_currentStreak_idx" RENAME TO "users_orgId_currentStreak_idx";
ALTER INDEX "users_tenantId_email_idx" RENAME TO "users_orgId_email_idx";
ALTER INDEX "users_tenantId_employeeId_key" RENAME TO "users_orgId_employeeId_key";
ALTER INDEX "users_tenantId_grade_idx" RENAME TO "users_orgId_grade_idx";
ALTER INDEX "users_tenantId_parentCode_key" RENAME TO "users_orgId_parentCode_key";
ALTER INDEX "users_tenantId_parentEmail_idx" RENAME TO "users_orgId_parentEmail_idx";
ALTER INDEX "users_tenantId_role_idx" RENAME TO "users_orgId_role_idx";
ALTER INDEX "users_tenantId_studentId_key" RENAME TO "users_orgId_studentId_key";
ALTER INDEX "users_tenantId_totalPoints_idx" RENAME TO "users_orgId_totalPoints_idx";
