/**
 * Curated icon set, re-exported behind @quikit/ui so the underlying library
 * (lucide-react today) can be swapped for QuikIT's set at merge by editing only
 * this file. Components import icons from "@quikit/ui", never "lucide-react".
 */
export {
  Hash,
  Search,
  Plus,
  Users,
  Info,
  LayoutGrid,
  ExternalLink,
  Send,
  Paperclip,
  Smile,
  SmilePlus,
  CheckCheck,
  Pin,
  PinOff,
  MessageSquare,
  MessageSquarePlus,
  LogOut,
  WifiOff,
  FileText,
  Download,
  Image as ImageIcon,
  Video,
  VideoOff,
  Mic,
  MicOff,
  Phone,
  PhoneOff,
  PhoneIncoming,
  PhoneOutgoing,
  PhoneMissed,
  Voicemail,
  Headphones,
  // Settings → Support Status.
  LifeBuoy,
  // Voice typing (dictation). A waveform, deliberately NOT `Mic` — the mic
  // button stages a voice-note attachment, this one types text into the editor,
  // and one icon for both outcomes would be genuinely ambiguous.
  AudioLines,
  Play,
  Pause,
  CornerUpRight,
  Reply,
  Forward,
  Pencil,
  MoreHorizontal,
  Copy,
  Trash2,
  X,
  Check,
  Bell,
  AtSign,
  Tag,
  Heart,
  MessageCircle,
  Settings,
  AlertCircle,
  Bold,
  Italic,
  Strikethrough,
  Code,
  Code2,
  Link as LinkIcon,
  List,
  Sun,
  Moon,
  Monitor,
  Calendar,
  CalendarPlus,
  Clock,
  MapPin,
  Inbox,
  Archive,
  Filter,
  Sparkles,
  Folder,
  Star,
  ChevronDown,
  ChevronLeft,
  BadgeCheck,
  EyeOff,
  Type,
  Palette,
  Shield,
  type LucideIcon,
} from "lucide-react";
