/**
 * Term sheet — print view.
 *
 * Auto-triggers the browser print dialog. The browser's "Save as PDF"
 * destination produces the PDF file. Suffix `?auto=0` to preview without
 * the dialog popping.
 *
 * Why client-side print (v1):
 *   - Zero new deps (no puppeteer / chromium runtime).
 *   - Works identically on local + Vercel.
 *   - Browser PDF engine handles CSS pagination cleanly.
 *
 * v2 path (server-rendered PDF endpoint):
 *   1. Add deps: `puppeteer-core`, `@sparticuz/chromium`
 *   2. New route: app/api/term-sheets/[id]/pdf/route.ts
 *      → spawn chromium, navigate to this print page with auto=0,
 *      → page.pdf() → return as application/pdf
 *   3. Add "Download PDF" button to term-sheet-client.tsx that hits the API
 *
 * For now the user clicks "Save as PDF" in the OS print dialog, which is
 * standard transactional-doc UX.
 */
import { notFound } from "next/navigation";
import { getDevAwareSession } from "@/lib/dev-session";
import { db } from "@/lib/db";
import PrintAutoTrigger from "./print-auto-trigger";

export const metadata = { title: "Term Sheet — Print" };

export default async function TermSheetPrintPage({
  params,
}: {
  params: { dealId: string };
}) {
  const session = await getDevAwareSession();
  const orgId = session?.user?.orgId;
  if (!orgId) notFound();

  const [ts, fundProfile] = await Promise.all([
    db.vCTermSheet.findUnique({
      where: { dealId: params.dealId },
      select: { version: true, renderedBodyHtml: true, updatedAt: true },
    }),
    db.vCFundProfile.findUnique({
      where: { orgId },
      select: { fundName: true },
    }),
  ]);

  if (!ts) notFound();

  return (
    <>
      <style dangerouslySetInnerHTML={{ __html: PRINT_CSS }} />
      <PrintAutoTrigger />

      <div className="ts-page">
        <header className="ts-header">
          <p className="ts-fund">{fundProfile?.fundName ?? "QuikVC"}</p>
          <p className="ts-meta">
            Term Sheet · v{ts.version} ·{" "}
            {new Date(ts.updatedAt).toLocaleDateString("en-IN", {
              day: "numeric", month: "long", year: "numeric",
            })}
          </p>
        </header>

        <main
          className="ts-body"
          dangerouslySetInnerHTML={{ __html: ts.renderedBodyHtml }}
        />

        <footer className="ts-footer">
          <p>Generated by QuikVC</p>
        </footer>
      </div>
    </>
  );
}

const PRINT_CSS = `
  @page { size: A4; margin: 20mm 18mm; }

  /* Reset Tailwind / next/font noise — we want a clean serif print look */
  body { background: #fff !important; color: #111 !important; margin: 0 !important; padding: 0 !important; }

  .ts-page {
    font-family: Georgia, "Times New Roman", serif;
    font-size: 11pt;
    line-height: 1.55;
    color: #111;
  }

  /* On screen, show the page in a centered "paper" preview */
  @media screen {
    body { background: #f3f3f5 !important; }
    .ts-page {
      max-width: 760px;
      margin: 24px auto;
      padding: 32px 40px;
      background: #fff;
      box-shadow: 0 1px 6px rgba(0,0,0,0.08);
    }
  }

  .ts-header {
    border-bottom: 2px solid #111;
    padding-bottom: 8px;
    margin-bottom: 24px;
    display: flex;
    justify-content: space-between;
    align-items: baseline;
  }
  .ts-fund {
    font-family: Helvetica, Arial, sans-serif;
    font-size: 14pt; font-weight: 700; margin: 0;
    letter-spacing: 0.02em;
  }
  .ts-meta {
    font-family: Helvetica, Arial, sans-serif;
    font-size: 9pt; color: #555; margin: 0;
  }

  .ts-body h1 { font-size: 16pt; margin: 24px 0 8px; }
  .ts-body h2 {
    font-size: 12pt; margin: 18px 0 6px;
    text-transform: uppercase; letter-spacing: 0.04em;
    border-bottom: 1px solid #999; padding-bottom: 2px;
  }
  .ts-body h3 { font-size: 11pt; margin: 14px 0 4px; font-weight: 700; }
  .ts-body p { margin: 6px 0; }
  .ts-body ul, .ts-body ol { margin: 4px 0 8px 18px; padding: 0; }
  .ts-body li { margin: 2px 0; }
  .ts-body table {
    border-collapse: collapse; width: 100%;
    margin: 12px 0; font-size: 10pt;
  }
  .ts-body th, .ts-body td {
    border: 1px solid #999; padding: 4px 8px;
    text-align: left; vertical-align: top;
  }
  .ts-body th {
    background: #f0f0f0;
    font-family: Helvetica, Arial, sans-serif;
    font-size: 9pt; text-transform: uppercase; letter-spacing: 0.04em;
  }

  /* Pagination niceties */
  .ts-body h2, .ts-body h3 { page-break-after: avoid; }
  .ts-body p, .ts-body li, .ts-body tr { page-break-inside: avoid; }

  .ts-footer {
    margin-top: 32px; padding-top: 8px;
    border-top: 1px solid #ccc;
    font-family: Helvetica, Arial, sans-serif;
    font-size: 8pt; color: #888; text-align: right;
  }

  @media print {
    .ts-header, .ts-footer { background: transparent; }
  }
`;
