export interface TzOption {
  value: string;
  label: string;
}

export const SUPPORTED_TIMEZONES: TzOption[] = [
  { value: "UTC", label: "UTC" },
  { value: "America/New_York", label: "Eastern Time (ET)" },
  { value: "America/Chicago", label: "Central Time (CT)" },
  { value: "America/Denver", label: "Mountain Time (MT)" },
  { value: "America/Los_Angeles", label: "Pacific Time (PT)" },
  { value: "America/Anchorage", label: "Alaska Time (AKT)" },
  { value: "Pacific/Honolulu", label: "Hawaii Time (HT)" },
  { value: "America/Toronto", label: "Eastern Time – Toronto" },
  { value: "America/Vancouver", label: "Pacific Time – Vancouver" },
  { value: "America/Mexico_City", label: "Central Time – Mexico City" },
  { value: "America/Sao_Paulo", label: "Brasília Time (BRT)" },
  { value: "America/Argentina/Buenos_Aires", label: "Argentina Time (ART)" },
  { value: "America/Bogota", label: "Colombia Time (COT)" },
  { value: "America/Lima", label: "Peru Time (PET)" },
  { value: "Europe/London", label: "Greenwich Mean Time (GMT)" },
  { value: "Europe/Dublin", label: "Irish Standard Time (IST)" },
  { value: "Europe/Paris", label: "Central European Time (CET)" },
  { value: "Europe/Berlin", label: "Central European Time – Berlin" },
  { value: "Europe/Madrid", label: "Central European Time – Madrid" },
  { value: "Europe/Rome", label: "Central European Time – Rome" },
  { value: "Europe/Amsterdam", label: "Central European Time – Amsterdam" },
  { value: "Europe/Warsaw", label: "Central European Time – Warsaw" },
  { value: "Europe/Athens", label: "Eastern European Time (EET)" },
  { value: "Europe/Istanbul", label: "Turkey Time (TRT)" },
  { value: "Europe/Moscow", label: "Moscow Standard Time (MSK)" },
  { value: "Africa/Cairo", label: "Eastern European Time – Cairo" },
  { value: "Africa/Nairobi", label: "East Africa Time (EAT)" },
  { value: "Africa/Lagos", label: "West Africa Time (WAT)" },
  { value: "Africa/Johannesburg", label: "South Africa Standard Time (SAST)" },
  { value: "Asia/Dubai", label: "Gulf Standard Time (GST)" },
  { value: "Asia/Riyadh", label: "Arabia Standard Time (AST)" },
  { value: "Asia/Karachi", label: "Pakistan Standard Time (PKT)" },
  { value: "Asia/Kolkata", label: "India Standard Time (IST)" },
  { value: "Asia/Colombo", label: "Sri Lanka Time (SLST)" },
  { value: "Asia/Dhaka", label: "Bangladesh Standard Time (BST)" },
  { value: "Asia/Kathmandu", label: "Nepal Time (NPT)" },
  { value: "Asia/Rangoon", label: "Myanmar Time (MMT)" },
  { value: "Asia/Bangkok", label: "Indochina Time (ICT)" },
  { value: "Asia/Jakarta", label: "Western Indonesia Time (WIB)" },
  { value: "Asia/Singapore", label: "Singapore Time (SGT)" },
  { value: "Asia/Kuala_Lumpur", label: "Malaysia Time (MYT)" },
  { value: "Asia/Manila", label: "Philippine Time (PHT)" },
  { value: "Asia/Shanghai", label: "China Standard Time (CST)" },
  { value: "Asia/Hong_Kong", label: "Hong Kong Time (HKT)" },
  { value: "Asia/Taipei", label: "Taiwan Standard Time (TST)" },
  { value: "Asia/Seoul", label: "Korea Standard Time (KST)" },
  { value: "Asia/Tokyo", label: "Japan Standard Time (JST)" },
  { value: "Australia/Perth", label: "Australian Western Time (AWST)" },
  { value: "Australia/Darwin", label: "Australian Central Time (ACST)" },
  { value: "Australia/Adelaide", label: "Australian Central Daylight Time (ACDT)" },
  { value: "Australia/Sydney", label: "Australian Eastern Time (AEST)" },
  { value: "Australia/Brisbane", label: "Australian Eastern Time – Brisbane" },
  { value: "Pacific/Auckland", label: "New Zealand Standard Time (NZST)" },
  { value: "Pacific/Fiji", label: "Fiji Time (FJT)" },
];
